# Generated by Django 2.2 on 2020-10-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201016_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-update', '-timestamp']},
        ),
    ]
