# Generated by Django 2.2 on 2020-10-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201016_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-update', '-publish_date', '-timestamp']},
        ),
    ]
